name: CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        cc:
          - gcc
          - clang
        make_target:
          - check
          - distcheck
        configure_flags:
          - --enable-luajit
          - --disable-luajit
          - --disable-luajit --disable-flush-jemalloc-tcache
        include:
          - cc: gcc
            make_target: lcov
            configure_flags: --enable-code-coverage

    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        run: |
          sudo apt update
          sudo DEBIAN_FRONTEND=noninteractive NEEDRESTART_SUSPEND=non-empty-value apt install -y \
            automake autotools-dev lcov libcurl4-gnutls-dev \
            libedit-dev libjemalloc-dev libncurses-dev \
            liblua5.1-0-dev libluajit-5.1-dev libpcre2-dev libtool lua5.1 \
            luajit python3-docutils python3-sphinx vim-common

      - name: Install Varnish Cache
        run: |
          wget --no-check-certificate https://varnish-cache.org/_downloads/varnish-8.0.0.tgz
          tar zxvf varnish-*.tgz
          pushd varnish-*/
          ./autogen.sh
          CC='${{ matrix.cc }}' ./configure
          make -sj32
          sudo make PREFIX='/usr/local' install
          sudo ldconfig
          popd

      - name: Build & test VMOD
        run: |
          ./autogen.sh
          CC='${{ matrix.cc }}' ./configure --prefix=/usr ${{ matrix.configure_flags }}
          make -j1
          make ${{ matrix.make_target }} -j1

      - name: Push code coverage
        if: ${{ matrix.make_target == 'lcov' }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

      - name: Show test report
        if: ${{ failure() }}
        run: |
          cat src/test-suite.log || exit 0
