name: CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        cc:
          - gcc
          - clang
        configure_flags:
          - --enable-luajit
          - --disable-luajit
          - --disable-luajit --disable-flush-jemalloc-tcache

    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        run: |
          sudo apt update
          sudo DEBIAN_FRONTEND=noninteractive NEEDRESTART_SUSPEND=non-empty-value apt install -y \
            automake autotools-dev lcov libcurl4-gnutls-dev \
            libedit-dev libeditline-dev libjemalloc-dev libncurses-dev \
            liblua5.1-0-dev libluajit-5.1-dev libpcre3-dev libtool lua5.1 \
            luajit python3-docutils python3-sphinx vim-common

      - name: Install Varnish Cache
        # Beware of the dirty hack required to compile VC 4.1 with clang.
        run: |
          wget --no-check-certificate https://varnish-cache.org/_downloads/varnish-4.1.10.tgz
          tar zxvf varnish-*.tgz
          pushd varnish-*/
          ./autogen.sh
          CC='${{ matrix.cc }}' \
            CFLAGS=$(if [ '${{ matrix.cc }}' == 'clang' ]; then echo '-Wno-implicit-int-float-conversion'; fi) \
            ./configure
          make -sj32
          sudo make PREFIX='/usr/local' install
          sudo ldconfig
          popd

      - name: Build & test VMOD
        run: |
          ./autogen.sh
          CC='${{ matrix.cc }}' ./configure --prefix=/usr ${{ matrix.configure_flags }}
          make -j1
          make check -j1
